// <auto-generated />
using DIAS.Infrasturcture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DIAS.RazorPages.Migrations
{
    [DbContext(typeof(StudyContext))]
    [Migration("20180111043037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIAS.Data.ImageRecord", b =>
                {
                    b.Property<int>("InstanceId");

                    b.Property<string>("DcmFileName")
                        .HasMaxLength(200);

                    b.Property<int>("ImageNumber");

                    b.Property<string>("ImageUID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Matrix")
                        .HasMaxLength(20);

                    b.Property<string>("SeriesUID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double?>("SliceThickness");

                    b.HasKey("InstanceId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("DIAS.Data.SeriesRecord", b =>
                {
                    b.Property<int>("InstanceId");

                    b.Property<string>("BodyPartExamined")
                        .HasMaxLength(50);

                    b.Property<int>("ImageCount");

                    b.Property<bool>("IsContrast");

                    b.Property<string>("Kernel")
                        .HasMaxLength(20);

                    b.Property<string>("ProtocolName")
                        .HasMaxLength(100);

                    b.Property<int>("RecordState");

                    b.Property<string>("SeriesDescription")
                        .HasMaxLength(200);

                    b.Property<string>("SeriesNumber")
                        .HasMaxLength(20);

                    b.Property<string>("SeriesType")
                        .HasMaxLength(20);

                    b.Property<string>("SeriesUID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("StudyUID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("InstanceId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("DIAS.Data.StudyRecord", b =>
                {
                    b.Property<int>("InstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DateTime");

                    b.Property<string>("Modality")
                        .HasMaxLength(10);

                    b.Property<string>("PatientAge")
                        .HasMaxLength(5);

                    b.Property<string>("PatientID")
                        .HasMaxLength(20);

                    b.Property<string>("PatientName")
                        .HasMaxLength(20);

                    b.Property<int>("PatientSex");

                    b.Property<int>("RecordState");

                    b.Property<string>("StudyDescription")
                        .HasMaxLength(200);

                    b.Property<string>("StudyID")
                        .HasMaxLength(30);

                    b.Property<string>("StudyUID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("InstanceId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("DIAS.Data.ImageRecord", b =>
                {
                    b.HasOne("DIAS.Data.SeriesRecord", "Series")
                        .WithMany("Images")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DIAS.Data.SeriesRecord", b =>
                {
                    b.HasOne("DIAS.Data.StudyRecord", "Study")
                        .WithMany("Series")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
